"""Stable, content-free local compute errors."""

from __future__ import annotations

from enum import Enum


class LocalComputeErrorCode(str, Enum):
    NOT_PAIRED = "NOT_PAIRED"
    SESSION_EXPIRED = "SESSION_EXPIRED"
    ORIGIN_NOT_ALLOWED = "ORIGIN_NOT_ALLOWED"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    AUTH_INVALID = "AUTH_INVALID"
    REPLAY_DETECTED = "REPLAY_DETECTED"
    UPDATE_REQUIRED = "UPDATE_REQUIRED"
    CAPABILITY_UNAVAILABLE = "CAPABILITY_UNAVAILABLE"
    INVALID_REQUEST = "INVALID_REQUEST"
    PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE"
    INTERNAL_COMPUTE_ERROR = "INTERNAL_COMPUTE_ERROR"
    INVALID_PDF = "INVALID_PDF"
    UNSUPPORTED_TEXTLESS_PDF = "UNSUPPORTED_TEXTLESS_PDF"
    DOCUMENT_CONFLICT = "DOCUMENT_CONFLICT"
    DOCUMENT_NOT_FOUND = "DOCUMENT_NOT_FOUND"
    JOB_NOT_FOUND = "JOB_NOT_FOUND"
    JOB_CANCELLED = "JOB_CANCELLED"
    MODEL_ARTIFACT_UNAVAILABLE = "MODEL_ARTIFACT_UNAVAILABLE"
    MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"
    MODEL_LOADING = "MODEL_LOADING"
    GENERATION_UNAVAILABLE = "GENERATION_UNAVAILABLE"
    GENERATION_TIMEOUT = "GENERATION_TIMEOUT"
    GENERATION_FAILED = "GENERATION_FAILED"
    INVALID_GENERATION_RESPONSE = "INVALID_GENERATION_RESPONSE"
    UNKNOWN_CITATION = "UNKNOWN_CITATION"
    PROVIDER_NOT_SUPPORTED = "PROVIDER_NOT_SUPPORTED"
    PLATFORM_CLOUD_DISABLED = "PLATFORM_CLOUD_DISABLED"
    USER_CLOUD_NOT_CONFIGURED = "USER_CLOUD_NOT_CONFIGURED"
    CREDENTIAL_UNAVAILABLE = "CREDENTIAL_UNAVAILABLE"
    CREDENTIAL_STORE_UNAVAILABLE = "CREDENTIAL_STORE_UNAVAILABLE"
    USER_CLOUD_UNREACHABLE = "USER_CLOUD_UNREACHABLE"
    USER_CLOUD_AUTH_FAILED = "USER_CLOUD_AUTH_FAILED"
    USER_CLOUD_RATE_LIMITED = "USER_CLOUD_RATE_LIMITED"
    USER_CLOUD_MODEL_UNAVAILABLE = "USER_CLOUD_MODEL_UNAVAILABLE"
    PREPARATION_FAILED = "PREPARATION_FAILED"
    CONTROL_CHANNEL_UNAVAILABLE = "CONTROL_CHANNEL_UNAVAILABLE"
    DEVICE_REVOKED = "DEVICE_REVOKED"
    CREDENTIAL_EPOCH_MISMATCH = "CREDENTIAL_EPOCH_MISMATCH"
    PROTOCOL_VERSION_UNSUPPORTED = "PROTOCOL_VERSION_UNSUPPORTED"
    MANIFEST_INVALID = "MANIFEST_INVALID"
    FORBIDDEN_MANIFEST_CONTENT = "FORBIDDEN_MANIFEST_CONTENT"
    GRANT_INVALID = "GRANT_INVALID"
    GRANT_SIGNATURE_INVALID = "GRANT_SIGNATURE_INVALID"
    GRANT_EXPIRED = "GRANT_EXPIRED"
    GRANT_ALREADY_CONSUMED = "GRANT_ALREADY_CONSUMED"
    GRANT_DEVICE_MISMATCH = "GRANT_DEVICE_MISMATCH"
    GRANT_EPOCH_MISMATCH = "GRANT_EPOCH_MISMATCH"
    ENDPOINT_GENERATION_MISMATCH = "ENDPOINT_GENERATION_MISMATCH"
    BROWSER_NONCE_MISMATCH = "BROWSER_NONCE_MISMATCH"
    GRANT_OPERATION_INVALID = "GRANT_OPERATION_INVALID"
    PLATFORM_VERIFICATION_KEY_UNAVAILABLE = "PLATFORM_VERIFICATION_KEY_UNAVAILABLE"
    SESSION_ESTABLISHMENT_FAILED = "SESSION_ESTABLISHMENT_FAILED"
    OPERATION_NOT_ALLOWED = "OPERATION_NOT_ALLOWED"
    SESSION_BINDING_INVALID = "SESSION_BINDING_INVALID"


_STATUS = {
    LocalComputeErrorCode.NOT_PAIRED: 503,
    LocalComputeErrorCode.SESSION_EXPIRED: 401,
    LocalComputeErrorCode.ORIGIN_NOT_ALLOWED: 403,
    LocalComputeErrorCode.AUTH_REQUIRED: 401,
    LocalComputeErrorCode.AUTH_INVALID: 401,
    LocalComputeErrorCode.REPLAY_DETECTED: 409,
    LocalComputeErrorCode.UPDATE_REQUIRED: 426,
    LocalComputeErrorCode.CAPABILITY_UNAVAILABLE: 503,
    LocalComputeErrorCode.INVALID_REQUEST: 400,
    LocalComputeErrorCode.PAYLOAD_TOO_LARGE: 413,
    LocalComputeErrorCode.INTERNAL_COMPUTE_ERROR: 500,
    LocalComputeErrorCode.INVALID_PDF: 400,
    LocalComputeErrorCode.UNSUPPORTED_TEXTLESS_PDF: 422,
    LocalComputeErrorCode.DOCUMENT_CONFLICT: 409,
    LocalComputeErrorCode.DOCUMENT_NOT_FOUND: 404,
    LocalComputeErrorCode.JOB_NOT_FOUND: 404,
    LocalComputeErrorCode.JOB_CANCELLED: 409,
    LocalComputeErrorCode.MODEL_ARTIFACT_UNAVAILABLE: 503,
    LocalComputeErrorCode.MODEL_UNAVAILABLE: 503,
    LocalComputeErrorCode.MODEL_LOADING: 503,
    LocalComputeErrorCode.GENERATION_UNAVAILABLE: 503,
    LocalComputeErrorCode.GENERATION_TIMEOUT: 504,
    LocalComputeErrorCode.GENERATION_FAILED: 502,
    LocalComputeErrorCode.INVALID_GENERATION_RESPONSE: 502,
    LocalComputeErrorCode.UNKNOWN_CITATION: 422,
    LocalComputeErrorCode.PROVIDER_NOT_SUPPORTED: 503,
    LocalComputeErrorCode.PLATFORM_CLOUD_DISABLED: 503,
    LocalComputeErrorCode.USER_CLOUD_NOT_CONFIGURED: 503,
    LocalComputeErrorCode.CREDENTIAL_UNAVAILABLE: 503,
    LocalComputeErrorCode.CREDENTIAL_STORE_UNAVAILABLE: 503,
    LocalComputeErrorCode.USER_CLOUD_UNREACHABLE: 503,
    LocalComputeErrorCode.USER_CLOUD_AUTH_FAILED: 502,
    LocalComputeErrorCode.USER_CLOUD_RATE_LIMITED: 429,
    LocalComputeErrorCode.USER_CLOUD_MODEL_UNAVAILABLE: 503,
    LocalComputeErrorCode.PREPARATION_FAILED: 422,
    LocalComputeErrorCode.CONTROL_CHANNEL_UNAVAILABLE: 503,
    LocalComputeErrorCode.DEVICE_REVOKED: 403,
    LocalComputeErrorCode.CREDENTIAL_EPOCH_MISMATCH: 403,
    LocalComputeErrorCode.PROTOCOL_VERSION_UNSUPPORTED: 426,
    LocalComputeErrorCode.MANIFEST_INVALID: 400,
    LocalComputeErrorCode.FORBIDDEN_MANIFEST_CONTENT: 400,
    LocalComputeErrorCode.GRANT_INVALID: 401,
    LocalComputeErrorCode.GRANT_SIGNATURE_INVALID: 401,
    LocalComputeErrorCode.GRANT_EXPIRED: 401,
    LocalComputeErrorCode.GRANT_ALREADY_CONSUMED: 409,
    LocalComputeErrorCode.GRANT_DEVICE_MISMATCH: 403,
    LocalComputeErrorCode.GRANT_EPOCH_MISMATCH: 403,
    LocalComputeErrorCode.ENDPOINT_GENERATION_MISMATCH: 409,
    LocalComputeErrorCode.BROWSER_NONCE_MISMATCH: 401,
    LocalComputeErrorCode.GRANT_OPERATION_INVALID: 403,
    LocalComputeErrorCode.PLATFORM_VERIFICATION_KEY_UNAVAILABLE: 503,
    LocalComputeErrorCode.SESSION_ESTABLISHMENT_FAILED: 503,
    LocalComputeErrorCode.OPERATION_NOT_ALLOWED: 403,
    LocalComputeErrorCode.SESSION_BINDING_INVALID: 401,
}


class LocalComputeError(Exception):
    def __init__(
        self,
        code: LocalComputeErrorCode,
        message: str | None = None,
        *,
        diagnostic_code: str | None = None,
    ):
        self.code = code
        # Durable local diagnostics may use a controlled code, never an
        # exception message or filesystem path.  API responses intentionally
        # expose only ``code`` and the safe public message.
        self.diagnostic_code = diagnostic_code
        self.message = message or code.value.replace("_", " ").title()
        super().__init__(self.message)

    @property
    def status_code(self) -> int:
        return _STATUS[self.code]
