"""Stable, content-free local compute errors."""

from __future__ import annotations

from enum import Enum


class LocalComputeErrorCode(str, Enum):
    NOT_PAIRED = "NOT_PAIRED"
    SESSION_EXPIRED = "SESSION_EXPIRED"
    ORIGIN_NOT_ALLOWED = "ORIGIN_NOT_ALLOWED"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    AUTH_INVALID = "AUTH_INVALID"
    REPLAY_DETECTED = "REPLAY_DETECTED"
    UPDATE_REQUIRED = "UPDATE_REQUIRED"
    CAPABILITY_UNAVAILABLE = "CAPABILITY_UNAVAILABLE"
    INVALID_REQUEST = "INVALID_REQUEST"
    PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE"
    INTERNAL_COMPUTE_ERROR = "INTERNAL_COMPUTE_ERROR"
    INVALID_PDF = "INVALID_PDF"
    UNSUPPORTED_TEXTLESS_PDF = "UNSUPPORTED_TEXTLESS_PDF"
    DOCUMENT_CONFLICT = "DOCUMENT_CONFLICT"
    DOCUMENT_NOT_FOUND = "DOCUMENT_NOT_FOUND"
    JOB_NOT_FOUND = "JOB_NOT_FOUND"
    JOB_CANCELLED = "JOB_CANCELLED"
    MODEL_ARTIFACT_UNAVAILABLE = "MODEL_ARTIFACT_UNAVAILABLE"
    MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"
    MODEL_LOADING = "MODEL_LOADING"
    GENERATION_UNAVAILABLE = "GENERATION_UNAVAILABLE"
    GENERATION_TIMEOUT = "GENERATION_TIMEOUT"
    GENERATION_FAILED = "GENERATION_FAILED"
    INVALID_GENERATION_RESPONSE = "INVALID_GENERATION_RESPONSE"
    UNKNOWN_CITATION = "UNKNOWN_CITATION"
    PROVIDER_NOT_SUPPORTED = "PROVIDER_NOT_SUPPORTED"
    PLATFORM_CLOUD_DISABLED = "PLATFORM_CLOUD_DISABLED"
    USER_CLOUD_NOT_CONFIGURED = "USER_CLOUD_NOT_CONFIGURED"
    CREDENTIAL_UNAVAILABLE = "CREDENTIAL_UNAVAILABLE"
    CREDENTIAL_STORE_UNAVAILABLE = "CREDENTIAL_STORE_UNAVAILABLE"
    USER_CLOUD_UNREACHABLE = "USER_CLOUD_UNREACHABLE"
    USER_CLOUD_AUTH_FAILED = "USER_CLOUD_AUTH_FAILED"
    USER_CLOUD_RATE_LIMITED = "USER_CLOUD_RATE_LIMITED"
    USER_CLOUD_MODEL_UNAVAILABLE = "USER_CLOUD_MODEL_UNAVAILABLE"
    PREPARATION_FAILED = "PREPARATION_FAILED"


_STATUS = {
    LocalComputeErrorCode.NOT_PAIRED: 503,
    LocalComputeErrorCode.SESSION_EXPIRED: 401,
    LocalComputeErrorCode.ORIGIN_NOT_ALLOWED: 403,
    LocalComputeErrorCode.AUTH_REQUIRED: 401,
    LocalComputeErrorCode.AUTH_INVALID: 401,
    LocalComputeErrorCode.REPLAY_DETECTED: 409,
    LocalComputeErrorCode.UPDATE_REQUIRED: 426,
    LocalComputeErrorCode.CAPABILITY_UNAVAILABLE: 503,
    LocalComputeErrorCode.INVALID_REQUEST: 400,
    LocalComputeErrorCode.PAYLOAD_TOO_LARGE: 413,
    LocalComputeErrorCode.INTERNAL_COMPUTE_ERROR: 500,
    LocalComputeErrorCode.INVALID_PDF: 400,
    LocalComputeErrorCode.UNSUPPORTED_TEXTLESS_PDF: 422,
    LocalComputeErrorCode.DOCUMENT_CONFLICT: 409,
    LocalComputeErrorCode.DOCUMENT_NOT_FOUND: 404,
    LocalComputeErrorCode.JOB_NOT_FOUND: 404,
    LocalComputeErrorCode.JOB_CANCELLED: 409,
    LocalComputeErrorCode.MODEL_ARTIFACT_UNAVAILABLE: 503,
    LocalComputeErrorCode.MODEL_UNAVAILABLE: 503,
    LocalComputeErrorCode.MODEL_LOADING: 503,
    LocalComputeErrorCode.GENERATION_UNAVAILABLE: 503,
    LocalComputeErrorCode.GENERATION_TIMEOUT: 504,
    LocalComputeErrorCode.GENERATION_FAILED: 502,
    LocalComputeErrorCode.INVALID_GENERATION_RESPONSE: 502,
    LocalComputeErrorCode.UNKNOWN_CITATION: 422,
    LocalComputeErrorCode.PROVIDER_NOT_SUPPORTED: 503,
    LocalComputeErrorCode.PLATFORM_CLOUD_DISABLED: 503,
    LocalComputeErrorCode.USER_CLOUD_NOT_CONFIGURED: 503,
    LocalComputeErrorCode.CREDENTIAL_UNAVAILABLE: 503,
    LocalComputeErrorCode.CREDENTIAL_STORE_UNAVAILABLE: 503,
    LocalComputeErrorCode.USER_CLOUD_UNREACHABLE: 503,
    LocalComputeErrorCode.USER_CLOUD_AUTH_FAILED: 502,
    LocalComputeErrorCode.USER_CLOUD_RATE_LIMITED: 429,
    LocalComputeErrorCode.USER_CLOUD_MODEL_UNAVAILABLE: 503,
    LocalComputeErrorCode.PREPARATION_FAILED: 422,
}


class LocalComputeError(Exception):
    def __init__(self, code: LocalComputeErrorCode, message: str | None = None):
        self.code = code
        self.message = message or code.value.replace("_", " ").title()
        super().__init__(self.message)

    @property
    def status_code(self) -> int:
        return _STATUS[self.code]
